// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ABCPharmacy
{
    public partial class ABCPharmacyContext : DbContext
    {
        public ABCPharmacyContext()
        {
        }

        public ABCPharmacyContext(DbContextOptions<ABCPharmacyContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Medicine> Medicines { get; set; }
    }
}