// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace LocusNine
{
    public partial class LocusNineContext : DbContext
    {
        public LocusNineContext()
        {
        }

        public LocusNineContext(DbContextOptions<LocusNineContext> options)
            : base(options)
        {
        }

        public virtual DbSet<User> Users { get; set; }
    }
}